def ask_question():
    print("who is the founder of facebook")
    print("Mark Zuckerberg")
    print("Bill Gates")
    print("steve Jobs")
    print("Larry Page")
ask_question()
ask_question()
ask_question()
ask_question()
ask_question()